Import('*')

SimObject('VectorOperations.py', sim_objects=['VectorOperations'])
Source('vector_operations.cc')
DebugFlag('VECTOR')
DebugFlag('ADDRESULT')
DebugFlag('DOTRESULT')
DebugFlag('NORMALIZE')



